"""bids

Revision ID: 99b585431393
Revises: a363768919cb
Create Date: 2024-12-08 00:31:17.898764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b585431393'
down_revision: Union[str, None] = 'a363768919cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managers',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('surname', sa.Text(), nullable=False),
    sa.Column('nickname', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('surname', sa.Text(), nullable=False),
    sa.Column('nickname', sa.Text(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids_x_employees',
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('bid_id', 'employee_id')
    )
    op.create_table('comments',
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spendings',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('bid_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bids', sa.Column('start_dttm', sa.DateTime(), nullable=False))
    op.add_column('bids', sa.Column('planned_end_dttm', sa.DateTime(), nullable=False))
    op.add_column('bids', sa.Column('actual_end_dttm', sa.DateTime(), nullable=True))
    op.add_column('bids', sa.Column('material_delivery_dttm', sa.DateTime(), nullable=True))
    op.add_column('bids', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('bids', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('bids', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'bids', 'bid_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bids', type_='foreignkey')
    op.drop_column('bids', 'deleted_at')
    op.drop_column('bids', 'created_at')
    op.drop_column('bids', 'category_id')
    op.drop_column('bids', 'material_delivery_dttm')
    op.drop_column('bids', 'actual_end_dttm')
    op.drop_column('bids', 'planned_end_dttm')
    op.drop_column('bids', 'start_dttm')
    op.drop_table('spendings')
    op.drop_table('comments')
    op.drop_table('bids_x_employees')
    op.drop_table('employees')
    op.drop_table('positions')
    op.drop_table('managers')
    op.drop_table('bid_categories')
    # ### end Alembic commands ###
